import type { OsculatingElements } from '@sss/tools/types';
import { describe, expect, it } from 'vitest';

import { meanAnomalyAt, orbitPolyline, periodDays, propagate, solveKepler } from './kepler.ts';

const DEG_TO_RAD = Math.PI / 180;

/** Earth's real heliocentric osculating elements, as generated by tools/. */
const EARTH: OsculatingElements = {
  id: 'earth',
  center: '500@10',
  epochJd: 2461041.5,
  eccentricity: 0.01591429536350342,
  periapsisKm: 147098602.1592249,
  inclinationDeg: 0.003549055731418342,
  ascendingNodeDeg: 177.6179030721728,
  argPeriapsisDeg: 286.3568704502947,
  periapsisTimeJd: 2461045.196355864,
  meanMotionDegPerSec: 0.00001142130337831415,
  meanAnomalyDeg: 356.3524337712979,
  trueAnomalyDeg: 356.2340674073986,
  semiMajorAxisKm: 149477430.1325314,
  apoapsisKm: 151856258.105838,
  periodSec: 31520045.31142557,
};

describe('solveKepler', () => {
  it('satisfies Kepler\'s equation for planetary eccentricities', () => {
    for (const e of [0, 0.0167, 0.0934, 0.2056, 0.2488]) {
      for (let deg = 0; deg < 360; deg += 17) {
        const M = deg * DEG_TO_RAD;
        const E = solveKepler(M, e);

        // solveKepler wraps M into [-pi, pi], so compare against the wrapped value.
        let wrappedM = M % (2 * Math.PI);
        if (wrappedM > Math.PI) wrappedM -= 2 * Math.PI;
        expect(E - e * Math.sin(E)).toBeCloseTo(wrappedM, 12);
      }
    }
  });

  it('converges for the high eccentricities comets will bring in phase B', () => {
    for (const e of [0.5, 0.8, 0.9, 0.967]) {
      for (let deg = 0; deg < 360; deg += 31) {
        const M = deg * DEG_TO_RAD;
        const E = solveKepler(M, e);

        expect(Number.isFinite(E)).toBe(true);
        let wrappedM = M % (2 * Math.PI);
        if (wrappedM > Math.PI) wrappedM -= 2 * Math.PI;
        expect(E - e * Math.sin(E)).toBeCloseTo(wrappedM, 10);
      }
    }
  });

  it('is the identity on a circular orbit', () => {
    expect(solveKepler(1.2, 0)).toBeCloseTo(1.2, 14);
  });
});

describe('propagate', () => {
  it('returns the epoch position when asked for the epoch', () => {
    const state = propagate(EARTH, EARTH.epochJd);
    const r = Math.hypot(state.position.x, state.position.y, state.position.z);

    // Earth is a few days from perihelion at this epoch, so ~0.983 AU.
    expect(r / 149_597_870.7).toBeCloseTo(0.9833, 3);
  });

  it('reproduces Earth\'s orbital speed', () => {
    const state = propagate(EARTH, EARTH.epochJd);
    const speed = Math.hypot(state.velocity.x, state.velocity.y, state.velocity.z);

    // Earth averages 29.78 km/s and is near perihelion here, so slightly faster.
    expect(speed).toBeGreaterThan(29.5);
    expect(speed).toBeLessThan(30.5);
  });

  it('returns to the same place after one full period', () => {
    const start = propagate(EARTH, EARTH.epochJd);
    const later = propagate(EARTH, EARTH.epochJd + periodDays(EARTH));

    // periodSec and meanMotionDegPerSec are rounded independently by Horizons and
    // disagree at the 1e-11 level, which is ~0.5 mm over Earth's orbit. Millimetres
    // is as tight as this can honestly be asserted.
    expect(later.position.x).toBeCloseTo(start.position.x, 2);
    expect(later.position.y).toBeCloseTo(start.position.y, 2);
    expect(later.position.z).toBeCloseTo(start.position.z, 2);
  });

  it('reaches periapsis and apoapsis at the right distances', () => {
    let closest = Infinity;
    let farthest = 0;
    const period = periodDays(EARTH);

    for (let i = 0; i <= 2000; i += 1) {
      const state = propagate(EARTH, EARTH.epochJd + (i / 2000) * period);
      const r = Math.hypot(state.position.x, state.position.y, state.position.z);
      closest = Math.min(closest, r);
      farthest = Math.max(farthest, r);
    }

    expect(closest).toBeCloseTo(EARTH.periapsisKm, -2);
    expect(farthest).toBeCloseTo(EARTH.apoapsisKm, -2);
  });

  it('is closest to the Sun at the reported time of periapsis', () => {
    const atPeriapsis = propagate(EARTH, EARTH.periapsisTimeJd);
    const r = Math.hypot(atPeriapsis.position.x, atPeriapsis.position.y, atPeriapsis.position.z);

    expect(r).toBeCloseTo(EARTH.periapsisKm, -1);
  });

  it('conserves specific angular momentum, as a two-body orbit must', () => {
    const period = periodDays(EARTH);
    const magnitudes: number[] = [];

    for (const fraction of [0, 0.13, 0.37, 0.61, 0.88]) {
      const { position: p, velocity: v } = propagate(EARTH, EARTH.epochJd + fraction * period);
      magnitudes.push(
        Math.hypot(
          p.y * v.z - p.z * v.y,
          p.z * v.x - p.x * v.z,
          p.x * v.y - p.y * v.x,
        ),
      );
    }

    for (const h of magnitudes) {
      expect(h).toBeCloseTo(magnitudes[0]!, 3);
    }
  });

  it('keeps velocity consistent with the position it reports', () => {
    // See the same check in hermite.test.ts for why h cannot be smaller: at a
    // Julian day of 2.46e6, float64 spacing limits how fine the step can usefully be.
    const jd = EARTH.epochJd + 40;
    const h = 1e-3;
    const before = propagate(EARTH, jd - h);
    const after = propagate(EARTH, jd + h);
    const state = propagate(EARTH, jd);

    const numericVx = (after.position.x - before.position.x) / (2 * h * 86_400);
    const numericVy = (after.position.y - before.position.y) / (2 * h * 86_400);

    expect(state.velocity.x / numericVx).toBeCloseTo(1, 6);
    expect(state.velocity.y / numericVy).toBeCloseTo(1, 6);
  });
});

describe('meanAnomalyAt', () => {
  it('advances by a full turn over one period', () => {
    const start = meanAnomalyAt(EARTH, EARTH.epochJd);
    const later = meanAnomalyAt(EARTH, EARTH.epochJd + periodDays(EARTH));

    expect(later - start).toBeCloseTo(2 * Math.PI, 6);
  });
});

describe('orbitPolyline', () => {
  it('produces a closed loop of the requested resolution', () => {
    const points = orbitPolyline(EARTH, 256);

    expect(points).toHaveLength(257);
    expect(points[256]!.x).toBeCloseTo(points[0]!.x, 6);
    expect(points[256]!.y).toBeCloseTo(points[0]!.y, 6);
  });

  it('spans exactly periapsis to apoapsis', () => {
    const radii = orbitPolyline(EARTH, 512).map((p) => Math.hypot(p.x, p.y, p.z));

    expect(Math.min(...radii)).toBeCloseTo(EARTH.periapsisKm, -1);
    expect(Math.max(...radii)).toBeCloseTo(EARTH.apoapsisKm, -1);
  });

  it('passes through the propagated positions', () => {
    // The drawn ellipse and the moving body must agree, or the planet visibly
    // drifts off its own orbit line.
    const points = orbitPolyline(EARTH, 2048);
    const state = propagate(EARTH, EARTH.epochJd + 100);

    const nearest = Math.min(
      ...points.map((p) => Math.hypot(p.x - state.position.x, p.y - state.position.y, p.z - state.position.z)),
    );

    // 2048 segments around a 1 AU orbit leaves ~460,000 km between points, so the
    // body must land well inside one segment of the polyline.
    expect(nearest).toBeLessThan(200_000);
  });
});
